version: '2'
services:
  esm1:
    image: elasticsearch:7.3.2
    container_name: esm1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdat1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  esm2:
    image: elasticsearch:7.3.2
    container_name: esm2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=esm1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdat2:/usr/share/elasticsearch/data
    networks:
      - esnet
  
  redis:
    image: redis

    ports:
      - "6379:6379"

volumes:
  esdat1:
    driver: local
  esdat2:
    driver: local

networks:
  esnet:
